from speedtest import Speedtest
from datetime import datetime

from bot import LOGGER
from bot.core.nuwa_client import TgClient
from bot.helper.ext_utils.bot_utils import new_task
from bot.helper.ext_utils.status_utils import get_readable_file_size
from bot.helper.telegram_helper.message_utils import (
    delete_message,
    edit_message,
    send_message,
)


@new_task
async def speedtest(_, message):
    status_message = await send_message(message, "Running network speed test, please wait...")

    def run_speedtest():
        test = Speedtest()
        test.get_best_server()
        test.download()
        test.upload()
        return test.results

    result = await TgClient.bot.loop.run_in_executor(None, run_speedtest)

    if not result:
        await edit_message(status_message, "Speedtest failed. Please try again later.")
        return

    # Format waktu uji
    raw_time = getattr(result, "timestamp", None)
    if raw_time:
        try:
            test_time = datetime.fromisoformat(raw_time).strftime("%Y-%m-%d %H:%M:%S")
        except Exception:
            test_time = raw_time
    else:
        test_time = "N/A"

    # Ambil jitter jika ada
    jitter = getattr(result, "jitter", "N/A")

    # Format laporan hasil speedtest
    output = (
        "<b>NETWORK SPEEDTEST REPORT</b>\n"
        "──────────────────────────────────────\n"
        "<pre>"
        f"{'Ping':15}: {result.ping:.2f} ms\n"
        f"{'Jitter':15}: {jitter if isinstance(jitter, (int, float)) else 'N/A'} ms\n"
        f"{'Download':15}: {get_readable_file_size(result.download / 8)}/s\n"
        f"{'Upload':15}: {get_readable_file_size(result.upload / 8)}/s\n"
        f"{'Server':15}: {result.server['name']}, {result.server['country']}\n"
        f"{'ISP':15}: {result.client['isp']}\n"
        f"{'IP Address':15}: {result.client['ip']}\n"
        f"{'Timestamp':15}: {test_time}\n"
        "</pre>"
        "──────────────────────────────────────\n"
        "<i>Report generated by NUWA Speedtest Service</i>"
    )

    try:
        await send_message(message, output)
        await delete_message(status_message)
    except Exception as e:
        LOGGER.error(f"Speedtest message send failed: {e}")
        await edit_message(status_message, output)